# Generated by Django 2.1.4 on 2018-12-27 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiments',
            name='accession',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='experiments',
            name='comparison',
            field=models.TextField(null=True),
        ),
    ]
