# Generated by Django 2.1.4 on 2018-12-27 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20181227_0636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiments',
            name='accession',
            field=models.CharField(max_length=150),
        ),
    ]
